name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test build UI
        run: npm run build

      - name: Check Formatting
        if: always()
        run: npm run check:formatting

      - name: Lint check
        if: always()
        run: npm run check:lint

      - name: Type check
        if: always()
        run: npm run check:types
